@echo off
set /p line= 
SET line=%line:a=A%
SET line=%line:b=B%
SET line=%line:c=C%
SET line=%line:d=D%
SET line=%line:e=E%
SET line=%line:f=F%
SET line=%line:g=G%
SET line=%line:h=H%
SET line=%line:i=I%
SET line=%line:j=J%
SET line=%line:k=K%
SET line=%line:l=L%
SET line=%line:m=M%
SET line=%line:n=N%
SET line=%line:o=O%
SET line=%line:p=P%
SET line=%line:q=Q%
SET line=%line:r=R%
SET line=%line:s=S%
SET line=%line:t=T%
SET line=%line:u=U%
SET line=%line:v=V%
SET line=%line:w=W%
SET line=%line:x=X%
SET line=%line:y=Y%
SET line=%line:z=Z%
ECHO %line%
