PLATFORM = EMSCRIPTEN
PLATFORM_LIBS = -LSDL2 -lz -lm 
PLATFORM_FLAGS = -DENDIAN_SDL -DHAS_SOCKLEN_T -DHAVE_UNISTD_H -DHAVE_INTTYPES_H -DHAVE_STDINT_H -DFLOATPOINT
PLATFORM_DIRECTORY = platform/sdl2
OBJDIR = objects-html
PLATFORMBITS = other
INCLUDE_PAWN = TRUE

CPP = python ${EMSCRIPTEN_ROOT}/em++
CC =  python ${EMSCRIPTEN_ROOT}/emcc
RES =
BIN  = luxengine.html
OPENGL = FALSE

NETWORK = FALSE
ONLINEENABLED = FALSE
NET_OBJECT = $(OBJDIR)/enet/unix.o

